// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyzwgumwdyespekxszbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5endndW13ZHllc3Bla3hzemJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMDIzNzAsImV4cCI6MjA2Mjc3ODM3MH0.InOVrDaTLDgPA0rjU7e4ek6k_W2aQrVxEjWuHH4ySio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);